{
 "title": "DMARC report",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Sent mails",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_range_begin AS \"time\",\n  domain AS metric,\n  count\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "elanis.eu - DKIM PASS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    dkim = 'pass' AND\n    domain = 'elanis.eu'\n  ORDER BY 1)::float /\n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    domain = 'elanis.eu' AND dkim <> ''\n  ORDER BY 1)::float * 100 as data"
    }
   ]
  },
  {
   "title": "elanis.eu - SPF PASS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    spf = 'pass' AND\n    domain = 'elanis.eu'\n  ORDER BY 1)::float /\n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    domain = 'elanis.eu' AND spf <> ''\n  ORDER BY 1)::float * 100 as data"
    }
   ]
  },
  {
   "title": "elanis.eu - DKIM PASS",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT dkim, COUNT(*)\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin) AND\n  domain = 'elanis.eu' AND dkim <> ''\nGROUP BY dkim"
    }
   ]
  },
  {
   "title": "elanis.eu - SPF PASS",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT spf, COUNT(*)\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin) AND\n  domain = 'elanis.eu' AND spf <> ''\nGROUP BY spf"
    }
   ]
  },
  {
   "title": "galactae.eu - DKIM PASS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    dkim = 'pass' AND\n    domain = 'galactae.eu'\n  ORDER BY 1)::float /\n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    domain = 'galactae.eu' AND dkim <> ''\n  ORDER BY 1)::float * 100 as data"
    }
   ]
  },
  {
   "title": "galactae.eu - SPF PASS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    spf = 'pass' AND\n    domain = 'galactae.eu'\n  ORDER BY 1)::float /\n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    domain = 'galactae.eu' AND spf <> ''\n  ORDER BY 1)::float * 100 as data"
    }
   ]
  },
  {
   "title": "galactae.eu - DKIM PASS",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT dkim, COUNT(*)\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin) AND\n  domain = 'galactae.eu' AND dkim <> ''\nGROUP BY dkim"
    }
   ]
  },
  {
   "title": "Quarentined mail",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_range_begin AS \"time\",\n  domain AS metric,\n  count\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin) AND\n  disposition = 'quarantine'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "galactae.eu - SPF PASS",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT spf, COUNT(*)\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin) AND\n  domain = 'galactae.eu' AND spf <> ''\nGROUP BY spf"
    }
   ]
  },
  {
   "title": "dysnomia.studio - DKIM PASS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    dkim = 'pass' AND\n    domain = 'dysnomia.studio'\n  ORDER BY 1)::float /\n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    domain = 'dysnomia.studio' AND dkim <> ''\n  ORDER BY 1)::float * 100 as data"
    }
   ]
  },
  {
   "title": "dysnomia.studio - SPF PASS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    spf = 'pass' AND\n    domain = 'dysnomia.studio'\n  ORDER BY 1)::float /\n  (SELECT\n    COUNT(*)\n  FROM feedback\n  WHERE\n    $__unixEpochFilter(date_range_begin) AND\n    domain = 'dysnomia.studio' AND spf <> ''\n  ORDER BY 1)::float * 100 as data"
    }
   ]
  },
  {
   "title": "dysnomia.studio - DKIM PASS",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT dkim, COUNT(*)\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin) AND\n  domain = 'dysnomia.studio' AND dkim <> ''\nGROUP BY dkim"
    }
   ]
  },
  {
   "title": "dysnomia.studio - SPF PASS",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT spf, COUNT(*)\nFROM feedback\nWHERE\n  $__unixEpochFilter(date_range_begin) AND\n  domain = 'dysnomia.studio' AND spf <> ''\nGROUP BY spf"
    }
   ]
  }
 ]
}