name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: v*
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
    - name: Build Dockerfile and Push to The Hub
      uses: firstmate-systems/docker-hub-builder@v1.0
      with:
        # The username to authenticate with dockerhub
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        # The token to authenticate with dockerhub
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
        # The tag of the base image
        BASE_TAG: latest
        # ARG input into Dockerfile for tag
        TAG_NAME: latest
        # Name of image to publish to dockerhub, e.g. 'user/my-image'
        IMAGE_NAME: dysnomiastudio/dmarc-parser
